MovieFan/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MovieFan.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MovieFan.Controllers
{
    public class MovieController : Controller
    {

        readonly MovieFanContext db;

        public MovieController( MovieFanContext db)
        {
            this.db = db;
        }
        // GET: Movie
        public ActionResult Index(int CategoryId)
        {
            List<SelectListItem> categories = db.Categories.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name, Selected = (x.Id == CategoryId) }).ToList();
            categories.Insert(0, new SelectListItem { Value = "0", Text= "(Toutes)" });
            ViewBag.Categories = categories;
            List<Movies> allmovies;
            if (CategoryId==0)
            {
                allmovies = db.Movies.Include(c => c.Category).Include(r => r.Rating).ToList();
            }
            else
            {
                allmovies = db.Movies.Where(m => m.CategoryId == CategoryId).Include(c => c.Category).Include(r => r.Rating).ToList();
            }
            return View(allmovies);
        }

        // GET: Movie/Details/5
        public ActionResult Details(int id)
        {
            List<SelectListItem> categories = db.Categories.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name.ToString() }).ToList();
            ViewBag.Categories = categories;
            ViewBag.ratings = db.Ratings.ToList();
            Movies movie = db.Movies.Include(c => c.Category).Include(r => r.Rating).First(m => m.Id == id);
            return View("Details",movie);
        }

        // GET: Movie/Create
        public ActionResult Create()
        {

            List<SelectListItem> categories = db.Categories.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name.ToString() }).ToList();
            ViewBag.Categories = categories;
            ViewBag.ratings = db.Ratings.ToList();
            Movies newMovie = new Movies();
            ViewBag.create = true;
            return View("Details", newMovie);
        }

        // POST: Movie/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult<Movies> Create([Bind("Title,Synopsis,CategoryId,RatingId")] Movies movie)
        {
            try
            {
                db.Movies.Add(movie);
                db.SaveChanges();
                TempData["flashmessage"] = "Film ajouté";
                TempData["flashmessagetype"] = "info";
                ViewBag.viewMode = Helpers.ViewModes.Show;
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                TempData["flashmessage"] = "Problème...";
                TempData["flashmessagetype"] = "danger";
                return RedirectToAction(nameof(Index));
            }
        }

        //// GET: Movie/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    //List<SelectListItem> categories = db.Categories.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name.ToString() }).ToList();
        //    //ViewBag.Categories = categories;
        //    //ViewBag.ratings = db.Ratings.ToList();
        //    //Movies movie = db.Movies.Include(c => c.Category).Include(r => r.Rating).First(m => m.Id == id);
        //    return View();
        //}

        // POST: Movie/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind("Title,Synopsis,CategoryId,RatingId,Picture,ReleaseDate")] Movies movie)
        {
            if (ModelState.IsValid)
                try
                {
                    movie.Id = id;
                    db.Update(movie);
                    db.SaveChanges();
                    TempData["flashmessage"] = "Changement enregistré";
                    TempData["flashmessagetype"] = "info";
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    TempData["flashmessage"] = "Un problème est survenu";
                    TempData["flashmessagetype"] = "danger";
                    ViewBag.viewMode = Helpers.ViewModes.Edit;
                    return View("Details", movie);
                }
            else {
                ViewBag.viewMode = Helpers.ViewModes.Edit;
                return Details(id);
            }
        }

        // GET: Movie/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Movie/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                db.Remove(db.Movies.First(m => m.Id == id));
                db.SaveChanges();
                TempData["flashmessage"] = "Film supprimé";
                TempData["flashmessagetype"] = "info";
            }
            catch
            {
                TempData["flashmessage"] = "Un problème est survenu";
                TempData["flashmessagetype"] = "danger";
                return View();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

MovieFan/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MovieFan.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MovieFan.Controllers
{
    public class UserController : Controller
    {
        readonly MovieFanContext db;

        public UserController(MovieFanContext db)
        {
            this.db = db;
        }
        // GET: User
        public ActionResult Index()
        {
            List<Users> users = db.Users.ToList();
            return View(users);
        }

        // GET: User/Details/5
        public ActionResult Details(int id)
        {
            Users user = db.Users
                   .Include(u=>u.UserLikeMovie)
                   .ThenInclude(ulm => ulm.Movie)
                   .SingleOrDefault(u => u.Id == id);
            return View(user);
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: User/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ManageMovies(int id)
        {
            Users user = db.Users
                   .Include(u => u.UserLikeMovie)
                   .ThenInclude(ulm => ulm.Movie)
                   .SingleOrDefault(u => u.Id == id);
            return View(user);
        }
    }
}

MovieFan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieFan</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/59acf71967.js" crossorigin="anonymous"></script>
    <script src="/js/movieFan.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieFan</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Films</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Membres</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Administration</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @if (TempData.Peek("flashmessage") != null)
    {
        <div class="alert alert-@TempData["flashmessagetype"] text-center" id="flashmessage"> @TempData["flashmessage"]</div>
    }
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MovieFan - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>